In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
dataset = pd.read_csv('Original_Dataset.csv')
X = dataset.iloc[:, 1:]
y = dataset.iloc[:, 0]

In [6]:
X['symptoms'] = 0
for i in range(len(X)):
  values = X.iloc[i].values.tolist()
  X['symptoms'][i] = [i for i in values[:-1] if str(i) != 'nan']



<ipython-input-6-6ddc01e0054c>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['symptoms'][i] = [i for i in values[:-1] if str(i) != 'nan']
C:\Users\user\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


In [7]:
 X['symptoms'][0]

['itching', ' skin_rash', ' nodal_skin_eruptions', ' dischromic _patches']

In [8]:
X.head()

Symptom_1              Symptom_2              Symptom_3  \
0     itching              skin_rash   nodal_skin_eruptions   
1   skin_rash   nodal_skin_eruptions    dischromic _patches   
2     itching   nodal_skin_eruptions    dischromic _patches   
3     itching              skin_rash    dischromic _patches   
4     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN   
1                   NaN       NaN       NaN       NaN       NaN       NaN   
2                   NaN       NaN       NaN       NaN       NaN       NaN   
3                   NaN       NaN       NaN       NaN       NaN       NaN   
4                   NaN       NaN       NaN       NaN       NaN       NaN   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        NaN        NaN        NaN   

  Symptom_16 Symptom_17                                           symptoms  
0        NaN        NaN  [itching,  skin_rash,  nodal_skin_eruptions,  ...  
1        NaN        NaN  [ skin_rash,  nodal_skin_eruptions,  dischromi...  
2        NaN        NaN  [itching,  nodal_skin_eruptions,  dischromic _...  
3        NaN        NaN        [itching,  skin_rash,  dischromic _patches]  
4        NaN        NaN       [itching,  skin_rash,  nodal_skin_eruptions]

In [10]:
res =   X[['symptoms']].join(pd.crosstab((s:= X['symptoms'].explode()).index, s))

In [12]:
X = res.iloc[:, 1:].values

In [13]:
X

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
y =  y.apply(lambda x: x.replace(' ' , '_'))



In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [17]:
y

array([15, 15, 15, ..., 38, 35, 27])

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 50)

In [19]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 200, random_state = 0)
regressor.fit(X_train , y_train)

RandomForestRegressor(n_estimators=200, random_state=0)

In [20]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=0)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[26. 26.]
 [28. 28.]
 [18. 18.]
 ...
 [36. 36.]
 [23. 23.]
 [29. 29.]]


In [21]:
y_pred = [round(i) for i in y_pred]


In [22]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9995543852661027

In [23]:
y_pred =le.inverse_transform(y_pred)
y_test =le.inverse_transform(y_test)

In [24]:
score = np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)

In [25]:
np.save('classes.npy', le.classes_)
import pickle
pickle.dump(regressor, open('Model.pkl', 'wb'))
